### ISSUE TITLE
Create binary sensor entities for simple RF codes (motion/door sensors)

### ISSUE THREAD

**Issue by danobot** [danobot/mqtt_payload_processor#1]
Given this:

```yaml

    - name: Motion Sensors
      type: binary
      mappings:
        mtn-living-room:
          type: motion
          payload: 2678906
        mtn-living-room-secondary:
          type: motion
          payload: 13690522
```

Create `binary_sensor` entities called `binary_sensor.mtn_living_room`, `binary_sensor.mtn_living_room_secondary` to the equivalent of defining them seperately:

```yaml
- platform: mqtt
  name: "living_room_motion"
  device_class: 'motion'
  state_topic: "/rf/2678906"
  off_delay: 2
```
